[package]
name = "uart_16550"
version = "0.1.0"
authors = ["Lachlan Sneff <lachlan.sneff@gmail.com>", "Philipp Oppermann <dev@phil-opp.com>"]
description = "Minimal support for uart_16550 serial output."
license = "MIT"

[dependencies]
bitflags = "1.0"
x86_64 = "0.5.4"
